name = "otp-backend"
main = "server.js"
compatibility_date = "2024-01-01"

[env.production]
name = "otp-backend-prod"

[env.staging]
name = "otp-backend-staging"

[build]
command = "npm run build"

[[env.production.vars]]
NODE_ENV = "production"

[[env.staging.vars]]
NODE_ENV = "staging" 